### ISSUE TITLE
BUG: Program points to Python 2 rather than Python 3 when attempting to run on Linux Mint 18

### ISSUE THREAD

**Issue by dominichayesferen** [lagru/Vivaldi-Thumbs-Replacer#4]
I think I found the solution to the previous issue when running it on Linux:
Following on from #3 , I've discovered that **if you run the program through the command 'python3', it will actually work** whereas if you run it alone, it seems to decide to use Python 2.7.X instead, you may want to look into the path of the command at the top of the program and replace it with Python3's command path instead @cuiba ...

**Comment by lagru** [comment]
I'm no expert with Linux but I think this issue is caused by the first line in this [file](https://github.com/cuiba/Vivaldi-Thumbs-Replacer/blob/master/vivaldiThumbsReplacer.py). `#!/usr/bin/env python` tells the OS to use the first python-interpreter located in its `$PATH`.

To make sure Python 3.x is used try modifying the first line to `#!/usr/bin/env python3`. If this works I'll commit the change.

**Comment by dominichayesferen** [comment]
1. Yeah, the top line conveys what to run the following code through, like #!/bin/bash makes a script work in bash for example
2. Yep, it works thank you! :)
